<div style="background-color:darkseagreen; padding: 18px; border-radius: 3px; text-align:center; font-size:2.5em; font-weight:bold; color:#222; margin-bottom:25px; letter-spacing:1px;">
Predicting Donor Response for Social Good 
</div>


# <h2 style="border-bottom: 4px solid darkseagreen; width:fit-content; margin: 0 auto 25px auto; padding-bottom:6px; font-weight:bold;">Exploratory Data Analysis</h2>

_Data Mining II 2025/2026_

Project by:
Francisco Gomes (20221810), Margarida Marchão (20221901), Marta Alves (20221890), Pedro Coimbras (20211573)

## 1.  Importing Needed libraries and data

In [2]:
#import needed libraries

#general use
import pandas as pd
import numpy as np

#visualization
import matplotlib as plt
import seaborn as sns

In [3]:
#import training data
data = pd.read_csv('project_data\donors_train.csv', index_col=0)

## 2. Initial Data Exploration

### Dataset overview

In [4]:
pd.set_option("display.max_columns", None)

data.head()

,CARD_PROM_12,CHILDREN,DONOR_AGE,DONOR_GENDER,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,HOME_OWNER,INCOME_GROUP,LAST_GIFT_AMT,LIFETIME_CARD_PROM,LIFETIME_GIFT_AMOUNT,LIFETIME_GIFT_COUNT,LIFETIME_MAX_GIFT_AMT,LIFETIME_MIN_GIFT_AMT,LIFETIME_PROM,MEDIAN_HOME_VALUE,MEDIAN_HOUSEHOLD_INCOME,MONTHS_SINCE_FIRST_GIFT,MONTHS_SINCE_LAST_GIFT,MONTHS_SINCE_LAST_PROM_RESP,NUMBER_PROM_12,PCT_ATTRIBUTE1,PCT_ATTRIBUTE2,PCT_ATTRIBUTE3,PCT_ATTRIBUTE4,PCT_OWNER_OCCUPIED,PEP_STAR,PER_CAPITA_INCOME,RECENCY_STATUS_96NK,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,SES,URBANICITY,WEALTH_RATING,TARGET_B
CONTROL_NUMBER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
61745,4.0,3.0,33.0,M,0.0,1.0,H,5.0,20.0,9.0,35.0,2.0,20.0,15.0,21.0,566.0,315.0,182.037132,18.0,18.0,10.0,0.0,52.0,17.0,25.0,92.0,0.0,12827.0,A,0.00,17.50,NaN,0.000,2.0,0.154,0.0,2,T,NaN,1
112703,3.0,2.0,NaN,F,1.0,1.0,U,NaN,15.0,6.0,15.0,1.0,15.0,15.0,15.0,318.0,148.0,24.000000,24.0,24.0,7.0,0.0,31.0,31.0,39.0,73.0,0.0,7787.0,N,15.00,15.00,1.0,0.250,1.0,0.100,0.0,3,R,NaN,1
166437,4.0,2.0,NaN,F,7.0,3.0,H,4.0,10.0,17.0,79.0,11.0,12.0,5.0,40.0,1669.0,373.0,129.000000,15.0,15.0,8.0,0.0,26.0,39.0,38.0,84.0,1.0,13965.0,S,0.00,10.67,0.0,0.000,3.0,0.231,1.0,1,U,NaN,0
170621,4.0,NaN,61.0,M,13.0,1.0,H,6.0,11.0,28.0,80.0,17.0,11.0,3.0,75.0,1464.0,488.0,130.000000,16.0,16.0,13.0,0.0,48.0,30.0,44.0,84.0,1.0,24123.0,A,10.00,10.00,2.0,0.286,2.0,0.111,0.0,1,U,NaN,0
44428,6.0,0.0,75.0,M,3.0,4.0,H,3.0,7.0,9.0,27.0,5.0,7.0,5.0,22.0,936.0,249.0,24.000000,17.0,17.0,13.0,0.0,52.0,NaN,66.0,90.0,1.0,15008.0,N,5.67,5.40,3.0,0.600,5.0,0.500,0.0,2,C,NaN,0

In [9]:
#check dataset shape
display(data.shape)

#check if index values are unique
is_unique = data.index.is_unique
print(f"Are index values unique? {is_unique}, with {len(data.index.unique())} out of {data.shape[0]} unique values.")

(13560, 40)

Are index values unique? True, with 13560 out of 13560 unique values.

Each record in the dataset corresponds to **one registered donor in the Civic Support Alliance database**, including both demographic and donation-related information

### Features and Feature Types

In [6]:
#checking data format and null count
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13560 entries, 61745 to 45722
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CARD_PROM_12                 13297 non-null  float64
 1   CHILDREN                     13298 non-null  float64
 2   DONOR_AGE                    10006 non-null  float64
 3   DONOR_GENDER                 13288 non-null  object
 4   FILE_CARD_GIFT               13300 non-null  float64
 5   FREQUENCY_STATUS_97NK        13278 non-null  float64
 6   HOME_OWNER                   13274 non-null  object
 7   INCOME_GROUP                 10271 non-null  float64
 8   LAST_GIFT_AMT                13299 non-null  float64
 9   LIFETIME_CARD_PROM           13300 non-null  float64
 10  LIFETIME_GIFT_AMOUNT         13287 non-null  float64
 11  LIFETIME_GIFT_COUNT          13285 non-null  float64
 12  LIFETIME_MAX_GIFT_AMT        13300 non-null  float64
 13  LIFETIME_MIN_GIFT_AMT        13279 non-null  float64
 14  LIFETIME_PROM                13306 non-null  float64
 15  MEDIAN_HOME_VALUE            13294 non-null  float64
 16  MEDIAN_HOUSEHOLD_INCOME      13290 non-null  float64
 17  MONTHS_SINCE_FIRST_GIFT      13290 non-null  float64
 18  MONTHS_SINCE_LAST_GIFT       13292 non-null  float64
 19  MONTHS_SINCE_LAST_PROM_RESP  13115 non-null  float64
 20  NUMBER_PROM_12               13289 non-null  float64
 21  PCT_ATTRIBUTE1               13286 non-null  float64
 22  PCT_ATTRIBUTE2               13299 non-null  float64
 23  PCT_ATTRIBUTE3               13288 non-null  float64
 24  PCT_ATTRIBUTE4               13295 non-null  float64
 25  PCT_OWNER_OCCUPIED           13292 non-null  float64
 26  PEP_STAR                     13292 non-null  float64
 27  PER_CAPITA_INCOME            13289 non-null  float64
 28  RECENCY_STATUS_96NK          13298 non-null  object
 29  RECENT_AVG_CARD_GIFT_AMT     13289 non-null  float64
 30  RECENT_AVG_GIFT_AMT          13292 non-null  float64
 31  RECENT_CARD_RESPONSE_COUNT   13294 non-null  float64
 32  RECENT_CARD_RESPONSE_PROP    13285 non-null  float64
 33  RECENT_RESPONSE_COUNT        13291 non-null  float64
 34  RECENT_RESPONSE_PROP         13285 non-null  float64
 35  RECENT_STAR_STATUS           13303 non-null  float64
 36  SES                          13287 non-null  object
 37  URBANICITY                   13291 non-null  object
 38  WEALTH_RATING                7290 non-null   float64
 39  TARGET_B                     13560 non-null  int64
dtypes: float64(34), int64(1), object(5)
memory usage: 4.7+ MB

In [11]:
#Visualising the absolute and relative amount of missing values in each feature
missing_counts = data.isna().sum()
missing_percent = (missing_counts / len(data)) * 100

missing_df = pd.DataFrame({
    'Missing Values': missing_counts.values,
    'Percent Missing': missing_percent.values
}, index=missing_counts.index)

missing_df = missing_df.sort_values(by='Percent Missing', ascending=False)

missing_df

                             Missing Values  Percent Missing
WEALTH_RATING                          6270        46.238938
DONOR_AGE                              3554        26.209440
INCOME_GROUP                           3289        24.255162
MONTHS_SINCE_LAST_PROM_RESP             445         3.281711
HOME_OWNER                              286         2.109145
FREQUENCY_STATUS_97NK                   282         2.079646
LIFETIME_MIN_GIFT_AMT                   281         2.072271
LIFETIME_GIFT_COUNT                     275         2.028024
RECENT_CARD_RESPONSE_PROP               275         2.028024
RECENT_RESPONSE_PROP                    275         2.028024
PCT_ATTRIBUTE1                          274         2.020649
LIFETIME_GIFT_AMOUNT                    273         2.013274
SES                                     273         2.013274
PCT_ATTRIBUTE3                          272         2.005900
DONOR_GENDER                            272         2.005900
RECENT_AVG_CARD_GIFT_AMT                271         1.998525
NUMBER_PROM_12                          271         1.998525
PER_CAPITA_INCOME                       271         1.998525
MONTHS_SINCE_FIRST_GIFT                 270         1.991150
MEDIAN_HOUSEHOLD_INCOME                 270         1.991150
URBANICITY                              269         1.983776
RECENT_RESPONSE_COUNT                   269         1.983776
RECENT_AVG_GIFT_AMT                     268         1.976401
PCT_OWNER_OCCUPIED                      268         1.976401
MONTHS_SINCE_LAST_GIFT                  268         1.976401
PEP_STAR                                268         1.976401
RECENT_CARD_RESPONSE_COUNT              266         1.961652
MEDIAN_HOME_VALUE                       266         1.961652
PCT_ATTRIBUTE4                          265         1.954277
CARD_PROM_12                            263         1.939528
RECENCY_STATUS_96NK                     262         1.932153
CHILDREN                                262         1.932153
PCT_ATTRIBUTE2                          261         1.924779
LAST_GIFT_AMT                           261         1.924779
FILE_CARD_GIFT                          260         1.917404
LIFETIME_CARD_PROM                      260         1.917404
LIFETIME_MAX_GIFT_AMT                   260         1.917404
RECENT_STAR_STATUS                      257         1.895280
LIFETIME_PROM                           254         1.873156
TARGET_B                                  0         0.000000

Preleminary conclusions:
- Seems like the only 2 columns that **do not** contain missing values are those relating to the customer ID and to the target variable (which explicits if the given person will donate)
- Some columns, like *WEALTH_RATING*, *DONOR_AGE*, *INCOME_GROUP* present a rate of missing values close or even higher than 25%, maybe requiring imputation or removal
- There are several groups of columns presenting the exact same number of missing values, suggesting that these features might be related and missing not at random.